version: '3.8'
services: 
  database:
    container_name: nba-cqrs-database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: nba_cqrs
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - '4306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
  php:
    container_name: nba-cqrs-php
    build:
      context: .
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/nba-cqrs
    depends_on:
      - database
  nginx:
    container_name: nba-cqrs-nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./app:/var/www/nba-cqrs
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
